// Code generated by cmd/reset. DO NOT EDIT.

package handler

func (r *responseWriter) Reset() {
	if r == nil {
		return
	}
	if resetter, ok := any(&r.ResponseWriter).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	r.status = 0
	r.size = 0
}

func (r *signResponseWriter) Reset() {
	if r == nil {
		return
	}
	if resetter, ok := any(&r.ResponseWriter).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if resetter, ok := any(&r.buf).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	r.statusCode = 0
}
